
[package]
name = "hyperstruc"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
nalgebra = "0.34.1"
num-rational = "0.4.2"
num-traits = "0.2.19"
permutation = "0.4.1"
rand = "0.9.2"
rayon = "1.10.0"
sets = "1.2.1"
uint = "0.10.0"

